name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:

      - name: Provide gfortran (macOS)
        if: runner.os == 'macOS'
        run: |
          # https://github.com/actions/virtual-environments/issues/2524
          # https://github.com/cbg-ethz/dce/blob/master/.github/workflows/pkgdown.yaml
          sudo ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          sudo mkdir /usr/local/gfortran
          sudo ln -s /usr/local/Cellar/gcc@11/*/lib/gcc/11 /usr/local/gfortran/lib
          gfortran --version

      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0     
        env:
          # Disable building for PyPy and 32bit
          # Disable musllinux because very slow (300s+ vs 20s)
          # Disable CPython3.6
          CIBW_SKIP: pp* *-win32 *_i686 *musllinux* cp36*
          # Run the tests against the built package
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/tests

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
