name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Fortran
        uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          # Disable building for PyPy, 32bit, musllinux
          CIBW_SKIP: pp* *-win32 *_i686 *musllinux*
          # Select only these Python versons
          CIBW_BUILD: cp310-* cp311-*
          # Additional configuration for builds
          CMAKE_GENERATOR: MinGW Makefiles
          CIBW_BUILD_FRONTEND: "pip"
          # Run the tests against the built package
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python -c "import apexpy"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
