name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1     
        env:
          # Disable building for PyPy, 32bit, musllinux
          CIBW_SKIP: pp* *-win32 *_i686 *musllinux*
          # Run the tests against the built package
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python -c "import apexpy"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
