name: Build wheels (attempt 2)

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels_v2:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            gcc_version: 15
          - os: windows-2025
            gcc_version: 15
          - os: ubuntu-24.04
            gcc_version: 13

    steps:
      - uses: actions/checkout@v4

      - name: Set up GCC on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-${{ matrix.gcc_version }} gfortran-${{ matrix.gcc_version }}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc_version }} 100
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.gcc_version }} 100
          gcc --version
          gfortran --version
      - name: Set up GCC on macOS
        if: runner.os == 'macOS'
        run: |
          brew install gcc@${{ matrix.gcc_version }}
          echo "CC=/opt/homebrew/bin/gcc-${{ matrix.gcc_version }}" >> $GITHUB_ENV
          echo "FC=/opt/homebrew/bin/gfortran-${{ matrix.gcc_version }}" >> $GITHUB_ENV
          /opt/homebrew/bin/gcc-${{ matrix.gcc_version }} --version
          /opt/homebrew/bin/gfortran-${{ matrix.gcc_version }} --version
      - name: Set up GCC on Windows
        if: runner.os == 'Windows'
        run: |
          choco install ninja mingw
          choco install rtools --no-progress
          echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH
          gfortran --version

      - name: Build wheels
        # https://github.com/pypa/cibuildwheel
        uses: pypa/cibuildwheel@v3.3.1
        env:
          # Select only these Python versons
          CIBW_BUILD: cp310-* cp311-* cp312-* cp313-* cp314-*
          # ...on these platforms
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS_MACOS: "arm64 x86_64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_BUILD_FRONTEND: "pip"
          # Run the tests against the built package
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python -c "import apexpy"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error
